//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wps_cool_csv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SettingsCsv : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsCsv defaultInstance = ((SettingsCsv)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsCsv())));
        
        public static SettingsCsv Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSaveEncode {
            get {
                return ((bool)(this["EnableSaveEncode"]));
            }
            set {
                this["EnableSaveEncode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableFreezeHeader {
            get {
                return ((bool)(this["EnableFreezeHeader"]));
            }
            set {
                this["EnableFreezeHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSelectHighlight {
            get {
                return ((bool)(this["EnableSelectHighlight"]));
            }
            set {
                this["EnableSelectHighlight"] = value;
            }
        }
    }
}
